version: '3.8'

services:

  my-mongodb:
    build:
      context: ..
      dockerfile: Dockerfile
    image: mongo:3.7
    container_name: mongodb-lc
    ports:
      - 27017:27017
    env_file:
      - env
    environment:
      MONGO_INITDB_ROOT_USERNAME: sdx
      MONGO_INITDB_ROOT_PASSWORD: passw
      MONGODB_DATA_DIR: /data/db
    volumes:
      # named volumes
      - ~/mongodb:/data/db

  sdx-lc:
    build:
      context: ..
      dockerfile: Dockerfile
    image: sdx-lc
    container_name: sdx-lc
    tty: true
    ports:
      - 8080:8080
    env_file:
      - env
    environment:
      - MONGODB_CONNSTRING=mongodb://sdx:passw@192.168.201.205:27017/
      - SDX_MQ_IP=152.54.3.143
      - SDXLC_DOMAIN=amlight
      # change to local controller host name
      - SDXLC_HOST=aw-sdx-lc-1.renci.org
      - SDXLC_PORT=8080
      - SDXLC_VERSION=1.0.0
      - PUB_TOPIC=topo
      - PUB_QUEUE=sdx_q1
      - SUB_QUEUE=connection
      - SUB_EXCHANGE=connection
      # change to local controller config (lcX_q1)
      - SUB_TOPIC=lc1_q1
      - MQ_NAME=hello
      - MQ_HOST=aw-sdx-monitor.renci.org
      - MQ_PORT=5672 
      - DB_NAME=test-db
      - DB_CONFIG_TABLE_NAME=sdx-config-test-1
      - DOMAIN_CONTROLLER_URL=http://192.168.201.205:8088/SDX-LC/1.0.0/provision
      - DOMAIN_CONTROLLER_PULL_URL=http://192.168.201.205:8088/SDX-LC/1.0.0/topology
      - DOMAIN_CONTROLLER_PULL_INTERVAL=180
      - KYTOS_URL=http://192.168.201.205:8088/SDX-LC/1.0.0/connection
